---
- name: Uninstall Cockpit dashboard.
  apt:
    name: >
      cockpit,
      cockpit-docker,
      cockpit-pcp
    state: absent

- name: "Create Cockpit folders."
  file:
    path: "{{ item.path }}"
    state: absent
    recurse: "{{ item.recurse }}"
  loop:
    - path: /etc/systemd/system/cockpit.socket.d
      recurse: false
