---
- name: Install Cockpit dashboard.
  apt:
    name: >
      cockpit,
      cockpit-docker,
      cockpit-pcp
    state: absent

- name: "Create Cockpit folders."
  file:
    path: "{{ item.path }}"
    state: directory
    recurse: "{{ item.recurse }}"
    state: absent
  loop:
    - path: /etc/systemd/system/cockpit.socket.d
      recurse: false
