---
- name: Add Node.js apt key.
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Add Node.js repositories.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_12.x {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_12.x {{ ansible_distribution_release }} main"
  register: node_repo

- name: Update apt cache if Node.js repo was added.
  apt:
    update_cache: yes
  when: node_repo.changed
  tags: ["skip_ansible_lint"]

- name: Ensure Node.js and npm are installed.
  apt:
    name: "nodejs=12.*"
    state: present
