---
- name: "admin : ensure group '{{ admin }}' exists"
  group:
    name: "{{ admin }}"
    state: present

- name: "admin : ensure user '{{ admin }}' exists"
  user:
    name: "{{ admin }}"
    password: "{{ admin_pass | password_hash('sha512') }}"
    group: "{{ admin }}"
    groups: sudo

- name: "admin : setup bash for '{{ admin }}'"
  command: "chsh -s /bin/bash {{ admin }}"
  changed_when: false

- name: "admin : add authorized keys"
  authorized_key:
    user: "{{ admin }}"
    state: present
    key: "{{ item.key }}"
  loop: "{{ auth_keys }}"

- name: "admin : remove deprecated authorized keys"
  authorized_key:
    user: "{{ admin }}"
    state: absent
    key: "{{ item.key }}"
  loop: "{{ auth_keys_deprecated }}"

- name: "admin : create folders"
  file:
    path: "{{ item.path }}"
    owner: "{{ admin }}"
    group: "{{ admin }}"
    state: directory
    recurse: "{{ item.recurse }}"
  loop:
    - path: "/home/{{ admin }}/.ssh"
      recurse: false
    - path: "/opt/sitepilot/services"
      recurse: false

- name: "admin : set admin home dir permission"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ admin }}"
    group: "{{ admin }}"
    mode: "0750"
  loop:
    - "/home/{{ admin }}"

- name: "admin : check if SSH keypair exists"
  stat:
    path: "/home/{{ admin }}/.ssh/id_rsa"
  register: ssh_keypair

- name: "admin : generate SSH keypair"
  openssh_keypair:
    path: /home/{{ admin }}/.ssh/id_rsa
  when: not ssh_keypair.stat.exists
