---
- name: "config : set the hostname"
  hostname:
    name: "{{ hostname }}"
  when:
    - hostname_update is defined
    - hostname_update|bool

- name: "config : set the timezone to '{{ timezone }}'"
  timezone:
    name: "{{ timezone }}"
  when:
    - timezone_update is defined
    - timezone_update|bool

- name: "config : set default home dir permission"
  lineinfile:
    path: /etc/adduser.conf
    regexp: "^DIR_MODE="
    line: "DIR_MODE=0750"
