---
- name: "fail2ban : install required packages"
  apt:
    name: "fail2ban"
    state: present

- name: "fail2ban : generate filter configuration"
  template:
    src: fail2ban_filter.j2
    dest: /etc/fail2ban/filter.d/app.conf

- name: "fail2ban : generate jail configuration"
  template:
    src: fail2ban_jail.j2
    dest: /etc/fail2ban/jail.d/app.conf

- name: "fail2ban : restart"
  service:
    name: fail2ban
    state: restarted
    enabled: true
