---
- name: "firewall : install required packages"
  apt:
    name: "ufw"
    state: present

- name: "firewall: configure the kernel to keep connections alive when enabling the firewall"
  sysctl:
    name: net.netfilter.nf_conntrack_tcp_be_liberal
    value: "1"
    state: present
    sysctl_set: true
    reload: true
  ignore_errors: true

- name: "firewall: remove default firewall rules"
  ufw:
    state: reset

- name: "firewall: configure firewall rules"
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    comment: "{{ item.name }}"
    from_ip: "{{ item.from_ip }}"
  loop: "{{ firewall }}"
  when:
    - ansible_ssh_host != 'autopilot-test'

- name: "firewall : enable firewall"
  ufw:
    state: enabled
  when:
    - ansible_ssh_host != 'autopilot-test'
