---
- name: "nodejs : download repository script"
  get_url:
    url: https://deb.nodesource.com/setup_12.x
    dest: /opt/sitepilot/scripts/nodejs-repo-install.sh
    mode: "0700"
    force: true

- name: "nodejs : install repository"
  shell: /opt/sitepilot/scripts/nodejs-repo-install.sh

- name: "nodejs : ensure Node.js and npm are installed"
  apt:
    name: "nodejs=12.*"
    state: present
