---
- name: "upgrade : configure unattended upgrades"
  template:
    src: upgrade_unattended.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: "upgrade : configure periodic upgrades"
  template:
    src: upgrade_periodic.j2
    dest: /etc/apt/apt.conf.d/10periodic

- name: "upgrade : upgrade packages to the latest version"
  apt:
    upgrade: dist
    force_apt_get: true
    update_cache: true
