---
- name: "root : configure root authorized keys"
  authorized_key:
    user: root
    state: present
    key: "{{ item.key }}"
  loop: "{{ auth_keys }}"

- name: "root : remove deprecated root authorized keys"
  authorized_key:
    user: root
    state: absent
    key: "{{ item.key }}"
  loop: "{{ auth_keys_deprecated }}"

- name: "root : create folders"
  file:
    path: "{{ item.path }}"
    owner: "root"
    group: "root"
    state: directory
    recurse: "{{ item.recurse }}"
    mode: "{{ item.mode }}"
  loop:
    - path: "/opt/sitepilot"
      recurse: false
      mode: "0755"
    - path: "/opt/sitepilot/users"
      recurse: false
      mode: "0755"
    - path: "/opt/sitepilot/scripts"
      recurse: false
      mode: "0700"
    - path: "/opt/sitepilot/ansible"
      recurse: false
      mode: "0777"
