---
- name: "ssmtp : install required packages"
  apt:
    name: "ssmtp"
    state: present

- name: "ssmtp : configure smtp relay"
  template:
    src: ssmtp_config.j2
    dest: /etc/ssmtp/ssmtp.conf
