---
- name: "{{ site.name }}: Write WordPress config."
  command: "{{ wp_cli_path }} config create --dbhost='{{ site.config.db_host }}' --dbname='{{ site.config.db_name }}' --dbuser='{{ site.config.db_user }}' --dbpass='{{ site.config.db_pass }}' --dbprefix='{{ site.config.db_prefix }}' --path={{ site.path }} --force"
  become: "{{ wp_become }}"
  become_user: "{{ site.user }}"
  when:
    - site.config.db_host is defined
    - site.config.db_name is defined
    - site.config.db_user is defined
    - site.config.db_pass is defined
    - site.config.db_prefix is defined

- name: "TEST {{ site.name }}: Domain is reachable."
  uri:
    url: "{{ site.url }}"
    validate_certs: false
  when:
    - site.url is defined
