#!/bin/bash
BASE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ -t 1 ]; then
    IT='-it'
else
    IT=''
fi

init() {
    mkdir -p $BASE/data/app
    mkdir -p $BASE/data/mysql
    mkdir -p $BASE/data/vendor
}

start() {
    init
    sudo docker-compose -f $BASE/docker-compose.yml --project-directory $BASE up -d
}

stop() {
    docker-compose -f $BASE/docker-compose.yml --project-directory $BASE down
}

restart() {
    init
    docker-compose -f $BASE/docker-compose.yml --project-directory $BASE restart
}

pull() {
    docker-compose -f $BASE/docker-compose.yml --project-directory $BASE pull
}

case "$1" in
'start') echo "Starting Autopilot Containers"
    start
    echo "DONE!"
    ;;
'stop') echo "Stopping Autopilot Containers"
    stop
    echo "DONE!"
    ;;
'restart') echo "Restarting Autopilot Containers"
    restart
    echo "DONE!"
    ;;
'install'|'install-test'|'install-dev') echo "Installing Autopilot"
    if [ "$1" == 'install-dev' ]; then
        cp $BASE/docker-compose.dev.yml $BASE/docker-compose.yml
    else
        curl -o $BASE/docker-compose.yml https://raw.githubusercontent.com/sitepilot/autopilot/master/docker-compose.prod.yml
    fi

    start

    echo "Waiting for containers..."
    sleep 10

    if [ ! -z "$2" ]; then
        docker exec $IT -w /var/www/html autopilot composer config http-basic.nova.laravel.com $2 $3
    fi

    docker exec $IT -w /var/www/html autopilot composer install --no-dev
    docker exec $IT -w /var/www/html autopilot php artisan key:generate
    docker exec $IT -w /var/www/html autopilot php artisan migrate --seed

    echo "DONE!"
    ;;
'update'|'update-test'|'update-dev') echo "Updating Autopilot"
    if [ "$1" == 'update-dev' ]; then
        cp $BASE/docker-compose.dev.yml $BASE/docker-compose.yml
    else
        curl -o $BASE/docker-compose.yml https://raw.githubusercontent.com/sitepilot/autopilot/master/docker-compose.prod.yml
    fi
    
    pull
    restart

    echo "Waiting for containers..."
    sleep 10

    docker exec $IT -w /var/www/html autopilot composer install --no-dev
    docker exec $IT -w /var/www/html autopilot php artisan migrate --seed

    echo "DONE!"
    ;;
'update-self') echo "Updating Autopilot Script"
    curl -o $BASE/autopilot https://raw.githubusercontent.com/sitepilot/autopilot/master/autopilot
    chmod +x $BASE/autopilot
    
    echo "DONE!"
    ;;
'exec')
    docker exec $IT -w /var/www/html autopilot "${@:2}"
    ;;
*)
    if [ "$(docker ps | grep autopilot-test)" ]; then
        echo "Starting sshd service in autopilot-test container..."
        docker exec $IT autopilot-test service sshd start
    fi
    docker exec $IT -w /var/www/html autopilot php artisan $@
    ;;
esac
