#!/bin/bash
if [ -t 1 ]; then
    IT='-it'
else
    IT=''
fi

case "$1" in
'install'|'install-test')  echo "Installing Autopilot"
    if [ "$1" == 'install-test'] 
        docker-compose up -f docker-compose.test.yml -d
    else
        docker-compose up -d
    fi

    echo "Waiting for containers..."
    sleep 5

    docker exec $IT -w /var/www/html autopilot composer install --no-dev
    docker exec $IT -w /var/www/html autopilot php artisan key:generate
    docker exec $IT -w /var/www/html autopilot php artisan migrate --seed

    echo "DONE!"
    ;;
'update')  echo "Updating Autopilot"
    docker pull sitepilot/autopilot:latest

    docker-compose up -d

    echo "Waiting for containers..."
    sleep 5

    docker exec $IT -w /var/www/html autopilot composer install --no-dev
    docker exec $IT -w /var/www/html autopilot php artisan migrate --seed

    echo "DONE!"
    ;;
'exec')
    docker exec $IT -w /var/www/html autopilot ${@:2}
    ;;
*)
    docker exec $IT -w /var/www/html autopilot php artisan ${@:2}
    ;;
esac
