version: "3.3"

services:
  mysql:
    image: mysql:8
    container_name: autopilot-mysql
    restart: always
    ports:
      - "${DB_HOST_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "mysql_data:/var/lib/mysql"

  web:
    image: sitepilot/autopilot-web:latest
    container_name: autopilot-web
    ports:
      - "${HTTP_HOST_PORT}:80"
      - "${HTTPS_HOST_PORT}:443"
      #- "7080:7080"
    restart: always
    environment:
      WEBSERVER_CACHE: "on"
      WEBSERVER_USER_ID: 1000
      WEBSERVER_USER_GID: 1000
      # SET_VHOST_FILE_PERMISSIONS: "yes"
    volumes:
      - type: bind
        source: "./"
        target: "/var/www/html"
        consistency: cached

volumes:
  mysql_data:
