version: "3.3"

services:
  mysql:
    image: mariadb:10.4-bionic
    container_name: autopilot-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "mysql_data:/var/lib/mysql"

  autopilot:
    image: sitepilot/autopilot-web:${APP_DOCKER_TAG}
    container_name: autopilot
    depends_on:
      - mysql
    ports:
      - "${APP_HTTP_PORT}:80"
      - "${APP_HTTPS_PORT}:443"
    restart: always
    environment:
      WEBSERVER_USER_ID: ${APP_USER_ID}
      WEBSERVER_USER_GID: ${APP_USER_GID}
      SET_VHOST_FILE_PERMISSIONS: "no"
    volumes:
      - type: bind
        source: "./"
        target: "/var/www/html"
        consistency: cached

volumes:
  mysql_data:
