version: "3.3"

services:
  database:
    image: mariadb:10.4-bionic
    container_name: autopilot-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "db_data:/var/lib/mysql"

  autopilot:
    image: sitepilot/autopilot-web:${APP_DOCKER_TAG}
    container_name: autopilot
    depends_on:
      - database
    ports:
      - "${APP_HTTP_PORT}:80"
      - "${APP_HTTPS_PORT}:443"
    restart: always
    environment:
      WEBSERVER_CACHE: "on"
      WEBSERVER_USER_ID: 1000
      WEBSERVER_USER_GID: 1000
      SET_VHOST_FILE_PERMISSIONS: "no"
    volumes:
      - type: bind
        source: "./"
        target: "/var/www/html"
        consistency: cached

volumes:
  db_data:
