version: "3.3"

services:
  mysql:
    image: mariadb:10.4-bionic
    container_name: autopilot-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "mysql_data:/var/lib/mysql"

  autopilot:
    image: sitepilot/autopilot-base:${APP_DOCKER_TAG}
    container_name: autopilot
    depends_on:
      - mysql
    ports:
      - "${APP_HTTP_PORT}:80"
      - "${APP_HTTPS_PORT}:443"
    restart: always
    environment:
      WEBSERVER_USER_ID: ${APP_USER_ID}
      WEBSERVER_USER_GID: ${APP_USER_GID}
      SET_VHOST_FILE_PERMISSIONS: "yes"
    volumes:
      - type: bind
        source: "./"
        target: "/var/www/html"
        consistency: cached
  
  dind:
    image: docker:latest
    container_name: autopilot-dind
    restart: always
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ''
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "autopilot_data:/opt/sitepilot"

  test:
    build: ./docker
    container_name: autopilot-test
    restart: always
    privileged: true
    ports:
      - "10080:80"
      - "10443:443"
      - "12083:2083"
    links:
      - "dind:docker-host"
    environment:
      DOCKER_HOST: 'tcp://docker-host:2375'
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "autopilot_data:/opt/sitepilot"

volumes:
  mysql_data:
  autopilot_data:
