version: "3.3"

services:
  mysql:
    image: mysql:8
    container_name: autopilot-mysql
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "mysql_data:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: autopilot-pma
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80

volumes:
  mysql_data:
