version: "3.3"

services:
  test:
    build: ./docker
    container_name: autopilot-test
    restart: always
    privileged: true
    ports:
      - "10080:80"
      - "10443:443"
      - "12083:2083"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
