---
- hosts: "{{ host }}"
  vars:
    user: ""
    app: ""
    domain: ""
    aliases: []
    email: ""
    ssl: true
    path: "/opt/sitepilot/users/{{ user }}/{{ app }}"
    path_vhost: "/usr/local/lsws/conf/vhosts/{{ app }}.conf"
  tasks:
    - name: "app cert : {{ user }} : {{ app }} : request ssl certificate"
      command: "certbot certonly --noninteractive --agree-tos --email {{ email }} --cert-name {{ app }} --webroot -w {{ path }}/public -d {{ domain }} {{ '-d ' + aliases|join(' -d ') if aliases is defined and aliases|length>0 else '' }}"

    - name: "app cert : {{ user }} : {{ app }} : regenerate vhost configuration"
      template:
        src: ./templates/olsws_app_vhost.j2
        dest: "{{ path_vhost }}"

    - name: "app cert : {{ user }} : {{ app }} : reload web server"
      service:
        name: lsws
        state: reloaded
