---
- name: "user : {{ user.name }} : install required pip packages"
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - PyMySQL

- name: "user : {{ user.name }} : remove apps"
  include_tasks: app.yml
  loop: "{{ user.apps }}"
  loop_control:
    loop_var: app
  when:
    - user.apps is defined

- name: "user : {{ user.name }} : remove user"
  user:
    name: "{{ user.name }}"
    state: absent
    force: true

- name: "user : {{ user.name }} : remove user group"
  group:
    name: "{{ user.name }}"
    state: absent

- name: "user : {{ user.name }} : remove user folders"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/home/{{ user.name }}"
    - "/opt/sitepilot/users/{{ user.name }}"

- name: "user : {{ user.name }} : remove database user"
  mysql_user:
    name: "{{ user.name }}"
    state: absent
    config_file: "/root/.my.cnf"
    host: "%"
  no_log: true

- name: "user : {{ user.name }} : remove user databases"
  mysql_db:
    name: "{{ item.name }}"
    state: "absent"
    config_file: "/root/.my.cnf"
  loop: "{{ user.databases }}"
  when:
    - user.databases is defined

- name: "user : {{ user.name }} : remove ssmtp alias"
  lineinfile:
    path: /etc/ssmtp/revaliases
    regexp: "^{{ user.name }}:"
    state: absent
