---
- name: "{{ site.name }}: Update WordPress plugins."
  command: "{{ wp_cli_path }} plugin update --all --path={{ site.path }}"
  become: "{{ wp_become }}"
  become_user: "{{ site.user }}"
  when:
    - "site.updates.plugins is defined"
    - "site.updates.plugins | bool"

- name: "{{ site.name }}: Update WordPress themes."
  command: "{{ wp_cli_path }} theme update --all --path={{ site.path }}"
  become: "{{ wp_become }}"
  become_user: "{{ site.user }}"
  when:
    - "site.updates.themes is defined"
    - "site.updates.themes | bool"

- name: "{{ site.name }}: Update WordPress core."
  command: "{{ wp_cli_path }} core update --path={{ site.path }}"
  become: "{{ wp_become }}"
  become_user: "{{ site.user }}"
  when:
    - "site.updates.core is defined"
    - "site.updates.core | bool"

- name: "TEST {{ site.name }}: Domain is reachable."
  uri:
    url: "{{ site.url }}"
    validate_certs: false
  when:
    - site.url is defined
