---
- name: reload olsws
  service:
    name: lsws
    state: reloaded

- name: restart ssh server
  service:
    name: sshd
    state: restarted

- name: restart docker
  service:
    name: docker
    state: restarted
  when:
    - autopilot_host is defined
    - not autopilot_host|bool

- name: reload fail2ban
  service:
    name: fail2ban
    state: reloaded
