---
- hosts: "{{ host }}"
  tasks:
    - name: "server/cert/renew : renew certificates"
      command: "certbot renew"
      register: cert_renew

    - name: "server/cert/renew : debug"
      debug:
        msg: "{{ cert_renew.stdout.split('\n') }}"
