---
- hosts: "{{ host }}"
  vars:
    admin: ""
    admin_pass: ""
    auth_keys: []
  tasks:
    # SSH Tests (when test public key is used)
    - name: "server/test : copy private key"
      copy:
        src: ./ssh/test_key
        dest: /root/.ssh/test_key
        owner: root
        group: root
        mode: "0600"

    - name: "server/test : can login over SSH using a private key as admin ({{ admin }})"
      command: "ssh -i /root/.ssh/test_key -o StrictHostKeyChecking=no -o BatchMode=yes {{ admin }}@127.0.0.1 'date'"
      when:
        - "auth_keys[0] is defined"
        - '"test@server" in auth_keys[0]'

    - name: "test/server : can login over SSH using a private key as root"
      command: "ssh -i /root/.ssh/test_key -o StrictHostKeyChecking=no -o BatchMode=yes root@127.0.0.1 'date'"
      when:
        - "auth_keys[0] is defined"
        - '"test@server" in auth_keys[0]'

    # MySQL Tests
    - name: "server/test : connect to MySQL as admin"
      command: "mysql -u {{ admin }} -p{{ admin_pass }} -h 127.0.0.1 -e 'show databases;'"
      changed_when: false

    # HTTP Checks
    - name: "server/test : web server is running (HTTP)"
      uri:
        url: http://127.0.0.1

    - name: "server/test : web server is running (HTTPS)"
      uri:
        url: https://127.0.0.1
        validate_certs: false

    - name: "server/test : web server admin panel is running (HTTPS)"
      uri:
        url: https://127.0.0.1:2083
        validate_certs: false

    - name: "test : phpMyAdmin is available"
      uri:
        url: https://127.0.0.1/.sitepilot/pma/
        validate_certs: false

    - name: "server/test : health check is available"
      uri:
        url: https://127.0.0.1/.sitepilot/pma/
        validate_certs: false

    # Other Checks
    - name: "server/test : PHP is installed"
      command: "php -v"
      become: true
      become_user: "{{ admin }}"
      changed_when: false

    - name: "server/test : PHP 7.4 is installed"
      command: "php74 -v"
      become: true
      become_user: "{{ admin }}"
      changed_when: false

    - name: "server/test : PHP 7.3 is installed"
      command: "php73 -v"
      become: true
      become_user: "{{ admin }}"
      changed_when: false

    - name: "server/test : WPCLI is installed"
      command: "wp --version"
      become: true
      become_user: "{{ admin }}"
      changed_when: false

    - name: "server/test : Composer is installed"
      command: "composer --version"
      become: true
      become_user: "{{ admin }}"
      changed_when: false

    - name: "server/test : Node.js is installed"
      command: "node -v"
      become: true
      become_user: "{{ admin }}"
      changed_when: false

    - name: "server/test : NPM is installed"
      command: "npm -v"
      become: true
      become_user: "{{ admin }}"
      changed_when: false
