---
- name: Enable Docker on startup.
  service:
    name: docker
    enabled: true

- name: "Check if Docker config file exists."
  stat:
    path: /etc/default/docker
  register: docker_config

- name: Configure Docker to preserve UFW rules.
  lineinfile:
    path: "/etc/default/docker"
    regex: "^DOCKER_OPTS="
    line: 'DOCKER_OPTS="--iptables=false"'
  notify:
    - restart docker
  when: docker_config.stat.exists

- name: "Check if Docker daemon config path exists."
  stat:
    path: /etc/docker
  register: docker_daemon_config

- name: Configure Docker daemon to preserve UFW rules.
  template:
    src: docker_daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
    - restart docker
  when: docker_daemon_config.stat.exists

- name: "Add user '{{ admin }}' to Docker group."
  user:
    name: "{{ admin }}"
    groups: docker
    append: true
