---
- name: Add Docker signing keys.
  apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - https://download.docker.com/linux/ubuntu/gpg

- name: Install Docker repositories.
  apt_repository:
    repo: "{{ item }}"
  loop:
    - "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: Install Docker CE.
  apt:
    name: docker-ce
