---
- name: Install MySQL python packages.
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - PyMySQL

- name: Copy .my.cnf file with 'root' credentials.
  template:
    src: "my-root.cnf.j2"
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: 0600

- name: Copy .my.cnf file with '{{ admin }}' credentials.
  template:
    src: "my-user.cnf.j2"
    dest: "/home/{{ admin }}/.my.cnf"
    owner: "{{ admin }}"
    group: "{{ admin }}"
    mode: 0600

- name: Ensure '{{ admin }}' user has admin rights.
  mysql_user:
    name: "{{ admin }}"
    password: "{{ admin_pass }}"
    priv: "*.*:ALL,GRANT"
    state: present
    host: "%"
    config_file: "/root/.my.cnf"
  register: result
  retries: 6
  delay: 10
  until: result is not failed
