---
- set_fact:
    sql_file_name: "{{ inventory_hostname }}_{{ site.name }}_{{ ansible_date_time.epoch }}.sql"
    zip_file_name: "{{ inventory_hostname }}_{{ site.name }}_{{ ansible_date_time.epoch }}.zip"

- set_fact:
    sql_file_path: "{{ site.path }}/{{ sql_file_name }}"
    zip_file_path: "{{ site.path }}/{{ zip_file_name }}"

- block:
    - name: "{{ site.name }}: Export WordPress database."
      command: "{{ wp_cli_path }} db export {{ sql_file_path }} --path={{ site.path }}"
      become: "{{ wp_become }}"
      become_user: "{{ site.user }}"

    - name: "{{ site.name }}: Compress site files."
      command: "zip -r {{ zip_file_path }} {{ site.path }}"
      become: "{{ wp_become }}"
      become_user: "{{ site.user }}"

    - name: "{{ site.name }}: Download export zip."
      fetch:
        src: "{{ zip_file_path }}"
        dest: "{{ export_folder }}/{{ zip_file_name }}"
        flat: true
  always:
    - name: "{{ site.name }}: Remove database export file."
      file:
        path: "{{ sql_file_path }}"
        state: absent
      become: "{{ wp_become }}"
      become_user: "{{ site.user }}"
    - name: "{{ site.name }}: Remove zip export file."
      file:
        path: "{{ zip_file_path }}"
        state: absent
      become: "{{ wp_become }}"
      become_user: "{{ site.user }}"
