---
- hosts: "{{ host }}"
  become: yes
  become_user: "{{ user }}"
  vars:
    user: ""
    app: ""
    update_exclude: []
    path: "/opt/sitepilot/users/{{ user }}/{{ app }}/public"
  tasks:
    - name: "wp/check-state : check if wp-config.php exists"
      stat:
        path: "{{ path }}/wp-config.php"
      register: wp_config

    - name: "wp/check-state : fail if wp-config.php doesn't exist"
      fail:
        msg: "WordPress is not installed."
      when: not wp_config.stat.exists

    - name: "wp/check-state : check core version"
      command: "wp core version --path={{ path }}"
      register: core_version

    - name: "wp/check-update : check for core updates"
      command: "wp core check-update --path={{ path }}"
      register: core_update_check
      changed_when: "'Success: WordPress is at the latest version.' not in core_update_check.stdout"

    - name: "wp/check-state : list plugins"
      command: "wp plugin list --format=json --path={{ path }}"
      register: plugin_list

    - name: "wp/check-update : check for plugin updates"
      command: "wp plugin update --all --exclude='{{ update_exclude|join(', ') }}' --dry-run --path={{ path }}"
      register: plugin_update_check
      changed_when: "'No plugin updates available.' not in plugin_update_check.stdout"

    - name: "wp/check-state : list themes"
      command: "wp theme list --format=json --path={{ path }}"
      register: theme_list

    - name: "wp/check-update : check for theme updates"
      command: "wp theme update --all --exclude='{{ update_exclude|join(', ') }}' --dry-run --path={{ path }}"
      register: theme_update_check
      changed_when: "'No theme updates available.' not in theme_update_check.stdout"

    - name: "wp/check-state : print data"
      debug:
        msg: "{{ item }}"
      loop:
        - "[autopilot-core-version]{{ core_version.stdout }}[/autopilot-core-version]"
        - "[autopilot-plugins]{{ plugin_list.stdout }}[/autopilot-plugins]"
        - "[autopilot-themes]{{ theme_list.stdout }}[/autopilot-themes]"
        - "[autopilot-has-update]{{ 'yes' if core_update_check.changed or plugin_update_check.changed or theme_update_check.changed else 'no' }}[/autopilot-has-update]"
