---
- hosts: "{{ host }}"
  become: yes
  become_user: "{{ user }}"
  vars:
    user: ""
    app: ""
    search: ""
    replace: ""
    path: "/opt/sitepilot/users/{{ user }}/{{ app }}/public"
  tasks:
    - name: "wp/search-replace : check if wp-config.php exists"
      stat:
        path: "{{ path }}/wp-config.php"
      register: wp_config

    - name: "wp/search-replace : fail if wp-config.php doesn't exist"
      fail:
        msg: "WordPress is not installed."
      when: not wp_config.stat.exists

    - name: "wp/search-replace : search and replace in database"
      command: "wp search-replace '{{ search }}' '{{ replace }}' --path={{ path }}"
