---
- hosts: "{{ host }}"
  become: yes
  become_user: "{{ user }}"
  vars:
    user: ""
    app: ""
    update_core: false
    update_plugins: false
    update_themes: false
    update_exclude: []
    path: "/opt/sitepilot/users/{{ user }}/{{ app }}/public"
  tasks:
    - name: "wp/update : check if wp-config.php exists"
      stat:
        path: "{{ path }}/wp-config.php"
      register: wp_config

    - name: "wp/update : fail if wp-config.php doesn't exist"
      fail:
        msg: "WordPress is not installed."
      when: not wp_config.stat.exists

    - name: "wp/update : update plugins"
      command: "wp plugin update --all --exclude='{{ update_exclude|join(', ') }}' --path={{ path }}"
      when: update_plugins | bool
      register: result
      changed_when: "'Success: Plugin already updated.' not in result.stdout"

    - name: "wp/update : update plugin translations"
      command: "wp language plugin update --all --path={{ path }}"
      when: update_plugins | bool
      register: result
      changed_when: "'Success: Translations are up to date.' not in result.stdout"

    - name: "wp/update : update themes"
      command: "wp theme update --all --exclude='{{ update_exclude|join(', ') }}' --path={{ path }}"
      when: update_themes | bool
      register: result
      changed_when: "'Success: Theme already updated.' not in result.stdout"

    - name: "wp/update : update theme translations"
      command: "wp language theme update --all --path={{ path }}"
      when: update_themes | bool
      register: result
      changed_when: "'Success: Translations are up to date.' not in result.stdout"

    - name: "wp/update : update core"
      command: "wp core update --path={{ path }}"
      when: update_core  | bool
      register: result
      changed_when: "'Success: WordPress is up to date.' not in result.stdout"

    - name: "wp/update : update core translations"
      command: "wp language core update --path={{ path }}"
      when: update_core | bool
      register: result
      changed_when: "'Success: Translations are up to date.' not in result.stdout"
