---
- name: "Create root owned folders."
  file:
    path: "{{ item }}"
    owner: "root"
    group: "root"
    state: directory
  loop:
    - "/opt/sitepilot"
    - "/opt/sitepilot/users"

- name: "Create admin owned folders."
  file:
    path: "{{ item.path }}"
    owner: "{{ admin }}"
    group: "{{ admin }}"
    state: directory
    recurse: "{{ item.recurse }}"
  loop:
    - path: "/opt/sitepilot/scripts"
      recurse: false
    - path: "/opt/sitepilot/services"
      recurse: false
