---
- name: Configure the kernel to keep connections alive when enabling the firewall.
  sysctl:
    name: net.netfilter.nf_conntrack_tcp_be_liberal
    value: "1"
    state: present
    sysctl_set: true
    reload: true
  ignore_errors: true

- name: Remove default firewall rules.
  ufw:
    state: reset

- name: Configure firewall rules.
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    comment: "{{ item.name }}"
    from_ip: "{{ item.from_ip }}"
  loop: "{{ firewall }}"

- name: Enable firewall.
  ufw:
    state: enabled
