---
name: Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install pip packages.
        run: sudo pip install ansible-lint && sudo pip install yamllint

      - name: Run Yaml lint on ansible folder.
        run: sudo yamllint -c tests/yamllint.yml ansible/

      - name: Run Ansible lint on ansible folder.
        run: sudo ansible-lint -v --force-color ansible/

      - name: Enable IPV6 for docker.
        run: |
          su -c "echo '{ \"ipv6\": true }' >> /etc/docker/daemon.json"
          sudo systemctl reload docker

      - name: Build container.
        run: docker build . --file Dockerfile --tag sitepilot/autopilot-base:${GITHUB_SHA}

      - name: Create environment file.
        run: |
          sudo cp .env.example .env
          sudo sed -i "s/APP_DOCKER_TAG=latest/APP_DOCKER_TAG=$GITHUB_SHA/" .env  
          sudo sed -i 's/APP_TEST_HOST=host.docker.internal/APP_TEST_HOST=172.17.0.1/' .env
          sudo sed -i 's/APP_TEST_PORT=7685/APP_TEST_PORT=22/' .env
          sudo sed -i 's/APP_TEST_AUTOPILOT_HOST=false/APP_TEST_AUTOPILOT_HOST=true/' .env

      - name: Run Autopilot installer.
        run: ./autopilot install-dev ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_PASSWORD }}

      - name: Test server:provision command.
        run: ./autopilot server:provision --host=test --skip-tags=upgrade --disable-tty

      - name: Test user:provision command.
        run: ./autopilot user:provision --user=test --disable-tty

      - name: Test app:provision command.
        run: ./autopilot app:provision --app=test --disable-tty

      - name: Test database:provision command.
        run: ./autopilot database:provision --database=test  --disable-tty

      - name: Test server:test command.
        run: ./autopilot server:test --host=test --disable-tty

      - name: Test user:test command.
        run: ./autopilot user:test --user=test --skip-tags=test-domains --disable-tty

      - name: Test database:destroy command.
        run: ./autopilot database:destroy --database=test --disable-tty

      - name: Test app:destroy command.
        run: ./autopilot app:destroy --app=test --disable-tty

      - name: Test user:destroy command.
        run: ./autopilot user:destroy --user=test --disable-tty

      - name: Deploy image to Docker hub.
        run: |
          if [[ ${GITHUB_REF##*/} = "master" ]]; then export DOCKER_TAG=latest; else export DOCKER_TAG=${GITHUB_REF##*/}; fi
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag sitepilot/autopilot-base:${GITHUB_SHA} sitepilot/autopilot-base:$DOCKER_TAG
          docker push sitepilot/autopilot-base:$DOCKER_TAG
