---
name: Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install pip packages.
        run: sudo pip install ansible-lint && sudo pip install yamllint

      - name: Run Yaml lint on ansible folder.
        run: sudo yamllint -c tests/yamllint.yml ansible/

      - name: Run Ansible lint on ansible folder.
        run: sudo ansible-lint -v --force-color ansible/

      - name: Stop MySQL server.
        run: sudo service mysql stop && sudo rm -rf /root/.my.cnf

      - name: Create environment file.
        run: |
          sudo cp .env.example .env
          sudo sed -i 's/APP_TEST_HOST=host.docker.internal/APP_TEST_HOST=172.17.0.1/' .env
          sudo sed -i 's/APP_TEST_PORT=7685/APP_TEST_PORT=22/' .env

      - name: Copy authorized keys file.
        run: |
          sudo cp ./vagrant/ssh/authorized_keys /root/.ssh/authorized_keys
          sudo chmod 600 /root/.ssh/authorized_keys

      - name: Build container.
        run: docker build . --file Dockerfile --tag sitepilot/autopilot:build-test

      - name: Start Autopilot containers.
        run: sudo docker-compose -f docker-compose.test.yml up -d

      - name: Authorize composer to install Nova.
        run: ./autopilot-exec composer config http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_PASSWORD }}

      - name: Install composer packages.
        run: ./autopilot-exec  composer install --no-dev

      - name: Generate application key.
        run: ./autopilot key:generate

      - name: Migrate the database.
        run: ./autopilot migrate --seed

      - name: Test server:provision command.
        run: ./autopilot server:provision --host=all --skip-tags=upgrade --disable-tty

      - name: Test server:test command.
        run: ./autopilot server:test --host=all --skip-tags=test-domains --disable-tty
