---
name: Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Debug ip.
        run: sudo ip addr

      - name: Install pip packages.
        run: sudo pip install ansible-lint && sudo pip install yamllint

      - name: Run Yaml lint on ansible folder.
        run: sudo yamllint -c tests/yamllint.yml ansible/

      - name: Run Ansible lint on ansible folder.
        run: sudo ansible-lint -v --force-color ansible/

      - name: Stop MySQL server.
        run: sudo service mysql stop && sudo rm -rf /root/.my.cnf

      - name: Create environment file.
        run: sudo sed 's/TEST_IP=192.168.25.100/TEST_IP=172.17.0.1/' .env.example > .env

      - name: Copy authorized keys file.
        run: | 
          sudo cp ./vagrant/ssh/authorized_keys /root/.ssh/authorized_keys
          sudo chmod 600 /root/.ssh/authorized_keys

      - name: Build container.
        run: docker build . --file Dockerfile --tag sitepilot/autopilot:test

      - name: Start Autopilot containers.
        run: sudo docker-compose -f docker-compose.test.yml up -d

      - name: Authorize composer to install Nova.
        run: docker exec -w /var/www/html autopilot-web composer config http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_PASSWORD }}

      - name: Install composer packages.
        run: docker exec -w /var/www/html autopilot-web composer install --no-dev

      - name: Generate application key.
        run: docker exec -w /var/www/html autopilot-web php artisan key:generate

      - name: Migrate the database.
        run: docker exec -w /var/www/html autopilot-web php artisan migrate --seed

      - name: Test sp:server:provision command.
        run: docker exec -w /var/www/html autopilot-web php artisan sp:server:provision --host=all --disable-tty

      - name: Test sp:server:test command.
        run: docker exec -w /var/www/html autopilot-web php artisan sp:server:test --host=all --skip-tags=test-domains --disable-tty
